#    vicon_mocap_package
#    Copyright (C) 2023 Jongwon Lee
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#    Author: David Hanley (dhanley@ed.ac.uk)
#    Maintainer: Jongwon Lee (jongwon5@illinois.edu)
#    Last date of change: 06/26/2023
Header header

std_msgs/Float64 quality_score
